version: '2'
services:
  solrnode1:
    image: docker.io/bitnami/solr:8
    environment:
      - SOLR_ENABLE_CLOUD_MODE=yes
      - SOLR_CLOUD_BOOTSTRAP=yes
      - SOLR_NUMBER_OF_NODES=1
      - SOLR_ZK_HOSTS=zk1:2181
      - SOLR_HOST=solrnode1
      - SOLR_ENABLE_AUTHENTICATION=yes
      - SOLR_ADMIN_USERNAME=solr
      - SOLR_ADMIN_PASSWORD=SolrRocks
    ports:
      - '8983:8983'
    volumes:
      - 'solr_data:/bitnami/solr'
  zk1:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zk1:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST=srvr,mntr,conf,ruok
  fcrepo:
    image: docker.io/samvera/fcrepo4:4.7.5
    ports:
      - '8080:8080'

volumes:
  solr_data:
    driver: local
  zookeeper_data:
    driver: local
