source "http://rubygems.org"

group :development, :test do
  gem "jeweler"
  gem "rspec", "<2.0.0"
  gem "mocha", ">= 0.9.8"
  gem "ruby-debug"
  gem "jettywrapper"
  gem "rcov"
  gem "yard"
  gem "RedCloth"
  gem "solrizer-fedora"
end

# Bundler will rely on active-fedora.gemspec (which is generated by Jeweler section of Rakefile) for runtime dependency information.

gemspec
