development:
  default:
    url: http://solr:SolrRocks@0.0.0.0:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
  full_text:
    url: http://solr:SolrRocks@0.0.0.0:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/development
test:
  default:
    url: http://solr:SolrRocks@0.0.0.0:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-test
  full_text:
    url: http://solr:SolrRocks@0.0.0.0:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/test
production:
  default:
    url: http://localhost:8080/solr/production
  full_text:
    url: http://localhost:8080/solr/production
